import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../../style.scss";
import { withSize } from "react-sizeme";
import { Responsive, WidthProvider } from "react-grid-layout";
import { useWindowSize } from "react-use";

const ResponsiveGridLayout = withSize({ refreshMode: "debounce" })(
  WidthProvider(Responsive)
);
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { width } = useWindowSize();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {width < 768 ? <BottomNav /> : <Sidebar />} */}
        {children}
      </body>
    </html>
  );
}
